version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGOVERSION}
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
      back_net:
        aliases:
          - post_db
          - comment_db
      front_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UIVERSION}
    ports:
      - ${PORTUI}
    networks:
      - reddit
      - back_net
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POSTVERSION}
    networks:
      - reddit
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENTVERSION}
    networks:
      - reddit
      - back_net
      - front_net
volumes:
  post_db:

networks:
  reddit:
  back_net:
  front_net:
