---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post.deployment
spec:
  replicas: 1
  selecctor:
    matchLabels:
     app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - image: chromko/post
        name: post
