---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongo-Deployment
spec:
  replicas: 1
  selecctor:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
        project: reddit
    spec:
      containers:
      - image: mongo:latest
        name: mongo
